# Generated by Django 2.0.1 on 2018-01-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questioner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('answers', models.CharField(max_length=4096)),
            ],
        ),
    ]
